fake shares functions w/ frontends
i'll need findimpl which is too much to copy&paste.

diff --git a/s/fake.in b/s/fake.in
--- a/s/fake.in
+++ b/s/fake.in
@@ -27,11 +27,6 @@ basex="${basex:-@basex@}"
 }
 # }}}
 
-basex() # {{{
-{
-  command "$basex" "$@"
-} # }}}
-
 usage() # {{{
 {
   local ex=${1-100}
@@ -65,6 +60,103 @@ EOF
   fi
   exit $ex
 } # }}}
+
+#### SHARED {{{
+
+basex() # {{{
+{
+  command "$basex" "$@"
+} # }}}
+
+catchalls() # {{{
+{
+  find "${1:?}" \
+    -mindepth 1 \
+    -maxdepth 1 \
+    -name '*+*' \
+  | sort -rn
+} # }}}
+
+findimpl() # {{{
+{
+  local rv=$1 impldir="$2" argc="$3" hargv="$4"
+  eval $rv=
+  if test -x "$impldir/$argc-$hargv"; then
+    eval $rv='"$impldir/$argc-$hargv"'
+    return
+  fi
+  local p=
+  for p in $(catchalls "$impldir"); do
+    local f="${p##*/}"
+    local fargc="${f%%+*}"
+    local fargv="${f#*+}"
+    [ $argc -ge $fargc ] || continue
+    if [ "$hargv" = "$fargv" ] || [ -z "$fargv" ]; then
+      eval $rv='"$p"'
+      return
+    fi
+    case "$hargv" in
+    "$fargv"-*)
+      eval $rv='"$p"'
+      return
+    ;;
+    esac
+  done
+  return 1
+} # }}}
+
+expected() # {{{
+{
+  local name="${1##*/}"
+  set --
+  if test "$name" = 0; then
+    :
+  else
+    local argc="${name%%[-+]*}"
+    local argv="${name#*[-+]}"
+    local arg=
+    local i=1
+    while test $i -le $argc; do
+      arg="${argv%%-*}"
+      argv="${argv#*-}"
+      set -- "$@" "$(printf -- "%s" "$arg" | basex -d base32hex)"
+      i=$((i+1))
+    done
+  fi
+  local fmt=
+  case "${name#$argc}" in
+  -*) fmt="fake: expected: %s\n" ;;
+  +*) fmt="fake: expected: %s [...]\n" ;;
+  esac
+  printf -- "$fmt" "$ARGV0${*:+ $*}"
+} # }}}
+
+mismatch() # {{{
+{
+  local impldir="$1" fname=
+  shift
+  printf -- "fake: error: argv mismatch\n"
+  find "$impldir" -mindepth 1 -print | sort | while read fname; do
+    expected "$fname"
+  done
+  printf -- "fake: received: %s" "$ARGV0"
+  test $# -eq 0 || printf -- " %s" "$@"
+  printf -- "\n"
+  exit 100
+} >&2 # }}}
+
+hashargs() # {{{
+{
+  local rv=$1 lhargv= arg=; shift
+  eval $rv=
+  for arg in "$@"; do
+    lhargv="$lhargv-$(printf -- "%s" "$arg" | basex -e base32hex)"
+  done
+  lhargv="${lhargv#-}"
+  eval $rv='"$lhargv"'
+} # }}}
+
+#### SHARED }}}
 
 catchall=0
 copy_body=nope
@@ -154,117 +246,26 @@ fi
 test -z "$exitcode" || printf -- >> "$name" "exit %s\n" "$exitcode"
 chmod +x "$name"
 
-sed '1,/^#### BEGIN FRONTEND$/d' < "$0" |
-sed \
-  -e "s#PATH#$PATH" \
-  -e "s#basex#$basex" \
-  -e "s#impldir#$impldir" \
-> "$frontend"
+{
+  printf '#!/bin/sh\n\n'
+  sed -n '/^#### SHARED {{{/,/### SHARED }}}/p' < "$0"
+  sed -n '/^#### BEGIN FRONTEND$/,$p' < "$0" |
+  sed \
+    -e "s#PATH#$PATH" \
+    -e "s#basex#$basex" \
+    -e "s#impldir#$impldir"
+} > "$frontend"
 chmod a+x "$frontend"
 exit
 
 #### BEGIN FRONTEND
-#!/bin/sh
 
 export PATH="#PATH#"
 
 impldir="#impldir#"
 basex="${basex:-#basex#}"
 
-basex() # {{{
-{
-  command "$basex" "$@"
-} # }}}
-
 export PATH="#PATH#"
-
-catchalls() # {{{
-{
-  find "${1:?}" \
-    -mindepth 1 \
-    -maxdepth 1 \
-    -name '*+*' \
-  | sort -rn
-} # }}}
-
-findimpl() # {{{
-{
-  local rv=$1 impldir="$2" argc="$3" hargv="$4"
-  eval $rv=
-  if test -x "$impldir/$argc-$hargv"; then
-    eval $rv='"$impldir/$argc-$hargv"'
-    return
-  fi
-  local p=
-  for p in $(catchalls "$impldir"); do
-    local f="${p##*/}"
-    local fargc="${f%%+*}"
-    local fargv="${f#*+}"
-    [ $argc -ge $fargc ] || continue
-    if [ "$hargv" = "$fargv" ] || [ -z "$fargv" ]; then
-      eval $rv='"$p"'
-      return
-    fi
-    case "$hargv" in
-    "$fargv"-*)
-      eval $rv='"$p"'
-      return
-    ;;
-    esac
-  done
-  return 1
-} # }}}
-
-expected() # {{{
-{
-  local name="${1##*/}"
-  set --
-  if test "$name" = 0; then
-    :
-  else
-    local argc="${name%%[-+]*}"
-    local argv="${name#*[-+]}"
-    local arg=
-    local i=1
-    while test $i -le $argc; do
-      arg="${argv%%-*}"
-      argv="${argv#*-}"
-      set -- "$@" "$(printf -- "%s" "$arg" | basex -d base32hex)"
-      i=$((i+1))
-    done
-  fi
-  local fmt=
-  case "${name#$argc}" in
-  -*) fmt="fake: expected: %s\n" ;;
-  +*) fmt="fake: expected: %s [...]\n" ;;
-  esac
-  printf -- "$fmt" "$ARGV0${*:+ $*}"
-} # }}}
-
-mismatch() # {{{
-{
-  local impldir="$1" fname=
-  shift
-  printf -- "fake: error: argv mismatch\n"
-  find "$impldir" -mindepth 1 -print | sort | while read fname; do
-    expected "$fname"
-  done
-  printf -- "fake: received: %s" "$ARGV0"
-  test $# -eq 0 || printf -- " %s" "$@"
-  printf -- "\n"
-  exit 100
-} >&2 # }}}
-
-hashargs() # {{{
-{
-  local rv=$1 lhargv= arg=; shift
-  eval $rv=
-  for arg in "$@"; do
-    lhargv="$lhargv-$(printf -- "%s" "$arg" | basex -e base32hex)"
-  done
-  lhargv="${lhargv#-}"
-  eval $rv='"$lhargv"'
-} # }}}
 
 hashargs hargv "$@"
 
